import { createFileRoute, Link, useParams, useSearch } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, Sparkles, Loader2, RefreshCw } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { MobileShell } from "@/components/MobileShell";
import { getCourse } from "@/lib/content";
import { getCustomRoutine } from "@/lib/routines";
import { fetchWellnessKnowledge } from "@/lib/gemini.functions";

type KnowledgeSearch = { step?: number };

export const Route = createFileRoute("/knowledge/$id")({
  component: KnowledgePage,
  validateSearch: (search: Record<string, unknown>): KnowledgeSearch => ({
    step: typeof search.step === "number" ? search.step : Number(search.step ?? 0) || 0,
  }),
  head: () => ({
    meta: [
      { title: "Wellness insight · QiWell" },
      { name: "description", content: "AI-guided TCM knowledge for your practice." },
    ],
  }),
  notFoundComponent: NotFound,
});

function NotFound() {
  return (
    <MobileShell showNav={false}>
      <div className="flex flex-1 flex-col items-center justify-center gap-3 p-8 text-center">
        <p className="text-lg font-semibold">Practice not found</p>
        <Link to="/catalog" className="text-sm font-semibold text-primary">
          Back to practices
        </Link>
      </div>
    </MobileShell>
  );
}

function KnowledgePage() {
  const { id } = useParams({ from: "/knowledge/$id" });
  const { step: stepParam } = useSearch({ from: "/knowledge/$id" });
  const course = getCourse(id) ?? getCustomRoutine(id);

  if (!course) return <NotFound />;

  const stepIndex = Math.min(Math.max(0, stepParam ?? 0), course.steps.length - 1);
  const step = course.steps[stepIndex];

  const query = useQuery({
    queryKey: ["knowledge", course.id, stepIndex, step.name],
    queryFn: () =>
      fetchWellnessKnowledge({
        data: {
          title: course.title,
          subtitle: course.subtitle,
          moveName: step.name,
          moveDetail: step.detail,
          goal: course.goal,
        },
      }),
    staleTime: 1000 * 60 * 30,
    retry: 0,
  });

  return (
    <MobileShell showNav={false}>
      <header className="flex items-center gap-3 px-5 pt-[max(env(safe-area-inset-top),1rem)]">
        <Link
          to="/session/$id"
          params={{ id: course.id }}
          className="flex size-9 items-center justify-center rounded-full border border-border bg-card"
          aria-label="Back to session"
        >
          <ChevronLeft className="size-5" />
        </Link>
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-semibold">{course.title}</p>
          <p className="truncate text-xs text-muted-foreground">{step.name}</p>
        </div>
      </header>

      <div className="px-5 pt-5">
        <div className="rounded-4xl border border-gold/50 bg-gradient-to-br from-gold/25 via-card to-sage/20 p-5">
          <div className="flex items-center gap-2">
            <span className="flex size-9 items-center justify-center rounded-2xl bg-card/80">
              <Sparkles className="size-4 text-gold-foreground" />
            </span>
            <div>
              <p className="text-xs font-semibold uppercase tracking-wide text-gold-foreground/80">
                Wellness insight
              </p>
              <p className="text-sm font-semibold">{step.name}</p>
            </div>
          </div>
          <p className="mt-3 text-xs text-muted-foreground">
            Generated by Gemini · educational content, not medical advice.
          </p>
        </div>
      </div>

      <main className="flex-1 px-5 pb-10 pt-5">
        {query.isPending && (
          <div className="flex flex-col items-center justify-center gap-3 rounded-4xl border border-border/60 bg-card p-10 text-center">
            <Loader2 className="size-6 animate-spin text-primary" />
            <p className="text-sm text-muted-foreground">Preparing your wellness insight…</p>
          </div>
        )}

        {query.isError && (
          <div className="rounded-4xl border border-destructive/40 bg-card p-6 text-center">
            <p className="text-sm font-semibold text-destructive">Couldn't reach Gemini</p>
            <p className="mt-2 text-xs text-muted-foreground">
              {(query.error as Error)?.message ?? "Please try again in a moment."}
            </p>
            <button
              onClick={() => query.refetch()}
              className="mt-4 inline-flex items-center gap-2 rounded-2xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"
            >
              <RefreshCw className="size-4" /> Try again
            </button>
          </div>
        )}

        {query.data && (
          <article className="rounded-4xl border border-border/60 bg-card p-6 shadow-card">
            <div className="space-y-3 text-sm leading-relaxed text-foreground/85 [&_h2]:mt-5 [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-foreground [&_h3]:mt-4 [&_h3]:font-semibold [&_h3]:text-foreground [&_ul]:list-disc [&_ul]:space-y-1.5 [&_ul]:pl-5 [&_ol]:list-decimal [&_ol]:space-y-1.5 [&_ol]:pl-5 [&_strong]:font-semibold [&_strong]:text-foreground [&_p]:leading-relaxed">
              <ReactMarkdown>{query.data.markdown}</ReactMarkdown>
            </div>
          </article>
        )}
      </main>
    </MobileShell>
  );
}
